# Generated by Django 2.2.6 on 2019-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dough', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_filling', models.CharField(max_length=255)),
                ('prise', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_pizza', models.CharField(max_length=255)),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Dough')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Filling')),
            ],
        ),
    ]
