# Generated by Django 2.2.6 on 2019-10-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='filling',
        ),
        migrations.AddField(
            model_name='filling',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza'),
            preserve_default=False,
        ),
    ]
