# Generated by Django 2.2.6 on 2019-10-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191019_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='dough',
        ),
        migrations.AddField(
            model_name='pizza',
            name='dough',
            field=models.ManyToManyField(to='pizza.Dough'),
        ),
    ]
