# Generated by Django 2.2.6 on 2019-10-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20191019_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filling',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='filling',
            field=models.ManyToManyField(to='pizza.Filling'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='dough',
        ),
        migrations.AddField(
            model_name='pizza',
            name='dough',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.Dough'),
            preserve_default=False,
        ),
    ]
