# Generated by Django 2.2.5 on 2019-10-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20191019_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='prise_pizza',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
