# Generated by Django 2.2.5 on 2019-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizza_prise_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='prise_pizza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
