# Generated by Django 2.2.5 on 2019-10-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_userinfoorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfFilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Овощи', 'Овощи'), ('Сыры', 'Сыры'), ('мясо', 'мясо'), ('рыба', 'рыба')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='filling',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.GroupOfFilling'),
            preserve_default=False,
        ),
    ]
