# Generated by Django 2.2.5 on 2019-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20191024_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupoffilling',
            name='group',
            field=models.CharField(max_length=50),
        ),
    ]
